#!/usr/local/bin/expect -f

set force_conservative 0  ;# set to 1 to force conservative mode even if
                          ;# script wasn't run conservatively originally
if {$force_conservative} {
	set send_slow {1 .1}
	proc send {ignore arg} {
		sleep .1
		exp_send -s -- $arg
	}
}

set timeout -1
spawn $env(JIRA_CLI) project delete_project $env(JIRA_PROJECT_KEY)
match_max 100000
expect -exact "Are you sure you want to delete the project key: CITS? \[y/n\] \[?25l"
send -- "y"
expect eof
