name: CI
on:
  push:
    branches-ignore:
      - main
    branches:
      - '**'
    tags-ignore:
      - '**'
    paths:
      - '.github/workflows/ci.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/*.rs'
      - '**/*.sh'
      - '**/*.exp'
  pull_request:
    paths:
      - '.github/workflows/ci.yml'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - '**/*.rs'
      - '**/*.sh'
      - '**/*.exp'

defaults:
  run:
    shell: bash

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: jira_cli
          cache-on-failure: true

      - name: Audit check
        run: |
          curl --location --output /tmp/cargo-audit.tar.gz https://github.com/rustsec/rustsec/releases/download/cargo-audit%2Fv0.16.0/cargo-audit-x86_64-unknown-linux-musl-v0.16.0.tgz
          tar --extract --verbose --gzip --file /tmp/cargo-audit.tar.gz --directory /usr/local/bin/ --strip-components=1 cargo-audit-x86_64-unknown-linux-musl-v0.16.0/cargo-audit
          cargo audit --json > $HOME/audit.json || exit 0

      - name: Check a local package and all of its dependencies for errors
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all

      - name: Lint check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

      - name: Outdated check
        run: |
          curl --output /usr/local/bin/cargo-outdated https://www.tuziwo.info/cargo-outdated-v0.10.2-x86_64-unknown-linux-gnu
          chmod a+x /usr/local/bin/cargo-outdated
          cargo outdated --depth 1 --format json > $HOME/outdated.json

      - name: Udeps check
        run: |
          curl --location --output /tmp/cargo-udeps.tar.gz https://github.com/est31/cargo-udeps/releases/download/v0.1.26/cargo-udeps-v0.1.26-x86_64-unknown-linux-gnu.tar.gz
          tar --extract --verbose --gzip --file /tmp/cargo-udeps.tar.gz --directory /usr/local/bin/ --strip-components=2 ./cargo-udeps-v0.1.26-x86_64-unknown-linux-gnu/cargo-udeps
          rustup install nightly
          cargo +nightly udeps --quiet --workspace --all-features --all-targets --output json > udeps.json || exit 0

      - name: Clippy check
        run: |
          rustup component add clippy
          cargo clippy --all-features --all-targets --message-format=json > $HOME/clippy.json || exit 0

      - name: Sonar converter
        working-directory: $HOME
        run: |
          cargo install cargo-sonar
          cargo sonar --issues audit,clippy,outdated,udeps

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3

      - name: Run sonarqube
        run: |
          sonar-scanner
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.sources=$GITHUB_WORKSPACE
          -Dsonar.host.url=${{ secrets.SONAR_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.externalIssuesReportPaths=$HOME/sonar.json

  test:
    runs-on: ${{ matrix.os }}
    needs:
      - check
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            rust: stable
            other: x86_64-unknown-linux-gnu
          - os: macos-latest
            rust: stable
            other: x86_64-apple-darwin
          - os: macos-latest
            rust: stable
            other: aarch64-apple-darwin
          - os: windows-latest
            rust: stable-msvc
            other: x86_64-pc-windows-msvc
          - os: windows-latest
            rust: stable-gnu
            other: x86_64-pc-windows-gnu
    steps:
      - uses: actions/checkout@v2
      - name: Update Rustup (temporary workaround)
        run: rustup self update
        shell: bash
        if: startsWith(matrix.os, 'windows')
      - run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
        name: Update Rustup and define default toolchain
      - run: rustup target add ${{ matrix.other }}
        name: Add target
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: jira_cli
          cache-on-failure: true
      - run: sudo apt update -y && sudo apt install expect gcc-multilib libsecret-1-0 libsecret-1-dev -y
        name: Install dependencies for Linux
        if: matrix.os == 'ubuntu-latest'
      - run: rustup component add rustfmt || echo "rustfmt not available"
        name: Install rustfmt
      - run: cargo build
        name: Build for all architecture except Mac ARM
        if: matrix.other != 'aarch64-apple-darwin'
      - run: |
          SDKROOT=$(xcrun -sdk macosx --show-sdk-path)
          MACOSX_DEPLOYMENT_TARGET=$(xcrun -sdk macosx --show-sdk-platform-version)
          cargo build --target=aarch64-apple-darwin
        name: Build for Mac ARM
        if: matrix.other == 'aarch64-apple-darwin'
      - run: ./tests.sh
        name: Run tests.sh
        env:
          JIRA_DOMAIN: ${{ secrets.JIRA_DOMAIN }}
          JIRA_USER: ${{ secrets.JIRA_USER }}
          JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
          JIRA_USER_ACCOUNT_ID: ${{ secrets.JIRA_USER_ACCOUNT_ID }}
        if: matrix.os == 'ubuntu-latest'
