name: Security audit
on:
  push:
    paths:
      - '**/Cargo.toml'
      - '**/Cargo.lock'
env:
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: Swatinem/rust-cache@v1
        with:
          sharedKey: jira_cli-check-security-audit
          cache-on-failure: true
      - uses: actions/checkout@v1

      - uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  cargo-deny:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        checks:
          - advisories
          - bans licenses sources
    continue-on-error: ${{ matrix.checks == 'advisories' }}
    steps:
      - uses: actions/checkout@v2
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.checks }}